// GENERATED by scripts/embed-dist.mjs — do not edit.
// Regenerate with `npm run embed:dist` (runs automatically during packaging).
//
// Checked in empty on purpose: `node server.ts` serves dist/ off disk so dev
// rebuilds are picked up live, and typecheck needs the module to resolve
// before any packaging has run.
export type EmbeddedFile = { contentType: string; body: string };

export const EMBEDDED_FRONTEND: Record<string, EmbeddedFile> = {};
