import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { AppSettings, DefinitionUrls, DiskCacheStatus } from '../shared/api.ts';
import { isJsonObject } from '../shared/json.ts';

export const DEFAULT_SETTINGS: AppSettings = {
    urls: {
        cmdline: 'https://raw.githubusercontent.com/Bluscream/vrchat-definitions/main/cmdline.csv',
        env: 'https://raw.githubusercontent.com/Bluscream/vrchat-definitions/main/env.csv',
        registry: 'https://raw.githubusercontent.com/Bluscream/vrchat-definitions/main/registry.csv',
        configSchema: 'https://raw.githubusercontent.com/Bluscream/vrchat-definitions/main/config.schema.json'
    },
    paths: {
        steamDir: '/run/media/system/Data/Games/Steam',
        wineBin: ''
    },
    cacheTtlMinutes: 60
};

export function getAppConfigDir(): string {
    if (process.platform === 'win32') {
        const appData = process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming');
        return path.join(appData, 'vrcx-extras');
    }
    const configHome = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), '.config');
    return path.join(configHome, 'vrcx-extras');
}

export function getConfigFile(): string {
    return path.join(getAppConfigDir(), 'config.toml');
}

export function getCacheDir(): string {
    return path.join(getAppConfigDir(), 'cache');
}

function ensureDirsExist() {
    const configDir = getAppConfigDir();
    const cacheDir = getCacheDir();
    if (!fs.existsSync(configDir)) fs.mkdirSync(configDir, { recursive: true });
    if (!fs.existsSync(cacheDir)) fs.mkdirSync(cacheDir, { recursive: true });
}

import TOML from '@iarna/toml';

function serializeSettingsToToml(settings: AppSettings): string {
    const tomlObj = {
        cache: {
            ttl_minutes: settings.cacheTtlMinutes
        },
        urls: {
            cmdline: settings.urls.cmdline,
            env: settings.urls.env,
            registry: settings.urls.registry,
            config_schema: settings.urls.configSchema
        },
        paths: {
            steam_dir: settings.paths?.steamDir || '',
            wine_bin: settings.paths?.wineBin || ''
        }
    };
    // TOML.stringify wants its own JsonMap; the object above is structurally
    // one, so this satisfies the library's nominal type without `any`.
    return (
        `# vrcx-extras Configuration File\n# Auto-generated by @iarna/toml\n\n` +
        TOML.stringify(tomlObj satisfies Record<string, Record<string, string | number>>)
    );
}

/** Reads a string field out of a parsed TOML table, or undefined if absent/wrong-typed. */
function tomlString(table: unknown, field: string): string | undefined {
    if (!isJsonObject(table)) {
        return undefined;
    }
    const value = table[field];
    return typeof value === 'string' ? value : undefined;
}

function parseTomlSettings(tomlStr: string): AppSettings {
    // config.toml is user-editable, so every field is checked rather than
    // assumed; anything missing or mistyped keeps its default.
    const parsed: unknown = TOML.parse(tomlStr);
    const root = isJsonObject(parsed) ? parsed : {};
    const settings: AppSettings = structuredClone(DEFAULT_SETTINGS);

    const cache = root['cache'];
    if (isJsonObject(cache) && typeof cache['ttl_minutes'] === 'number') {
        settings.cacheTtlMinutes = cache['ttl_minutes'];
    }

    const urls = root['urls'];
    settings.urls.cmdline = tomlString(urls, 'cmdline') ?? settings.urls.cmdline;
    settings.urls.env = tomlString(urls, 'env') ?? settings.urls.env;
    settings.urls.registry = tomlString(urls, 'registry') ?? settings.urls.registry;
    settings.urls.configSchema = tomlString(urls, 'config_schema') ?? settings.urls.configSchema;

    const paths = root['paths'];
    if (isJsonObject(paths)) {
        settings.paths ??= { ...DEFAULT_SETTINGS.paths };
        settings.paths.steamDir = tomlString(paths, 'steam_dir') ?? settings.paths.steamDir;
        settings.paths.wineBin = tomlString(paths, 'wine_bin') ?? settings.paths.wineBin;
    }

    return settings;
}

export function readSettings(): AppSettings {
    ensureDirsExist();
    const file = getConfigFile();
    if (!fs.existsSync(file)) {
        writeSettings(DEFAULT_SETTINGS);
        return DEFAULT_SETTINGS;
    }
    try {
        const content = fs.readFileSync(file, 'utf-8');
        return parseTomlSettings(content);
    } catch (err) {
        console.error('[Settings] Error reading config.toml:', err);
        return DEFAULT_SETTINGS;
    }
}

export function writeSettings(settings: AppSettings): boolean {
    ensureDirsExist();
    const file = getConfigFile();
    try {
        const tomlStr = serializeSettingsToToml(settings);
        fs.writeFileSync(file, tomlStr, 'utf-8');
        console.log(`[Settings] Updated config.toml at ${file}`);
        return true;
    } catch (err) {
        console.error('[Settings] Error writing config.toml:', err);
        return false;
    }
}

export function resetSettings(): AppSettings {
    writeSettings(DEFAULT_SETTINGS);
    return DEFAULT_SETTINGS;
}

export function getDiskCacheStatus(): DiskCacheStatus {
    ensureDirsExist();
    const cacheDir = getCacheDir();
    const filesInfo: Array<{ name: string; ageMinutes: number; sizeBytes: number }> = [];
    let totalSizeBytes = 0;

    try {
        const entries = fs.readdirSync(cacheDir);
        for (const entry of entries) {
            const filePath = path.join(cacheDir, entry);
            const stat = fs.statSync(filePath);
            if (stat.isFile()) {
                const ageMinutes = Math.floor((Date.now() - stat.mtimeMs) / 60000);
                totalSizeBytes += stat.size;
                filesInfo.push({
                    name: entry,
                    ageMinutes,
                    sizeBytes: stat.size
                });
            }
        }
    } catch {}

    return {
        count: filesInfo.length,
        totalSizeBytes,
        files: filesInfo
    };
}

export function clearDiskCache(): boolean {
    ensureDirsExist();
    const cacheDir = getCacheDir();
    try {
        const entries = fs.readdirSync(cacheDir);
        for (const entry of entries) {
            fs.unlinkSync(path.join(cacheDir, entry));
        }
        console.log('[Settings] Cleared disk cache folder');
        return true;
    } catch (err) {
        console.error('[Settings] Error clearing disk cache:', err);
        return false;
    }
}

export async function fetchDefinitionContent(name: keyof DefinitionUrls, forceRefresh = false): Promise<string> {
    ensureDirsExist();
    const settings = readSettings();
    const url = settings.urls[name];
    const fileName = `${name}.cache`;
    const cacheFile = path.join(getCacheDir(), fileName);

    const ttlMs = settings.cacheTtlMinutes * 60 * 1000;
    const isExpired = fs.existsSync(cacheFile)
        ? (Date.now() - fs.statSync(cacheFile).mtimeMs) > ttlMs
        : true;

    if (!forceRefresh && ttlMs > 0 && fs.existsSync(cacheFile) && !isExpired) {
        try {
            return fs.readFileSync(cacheFile, 'utf-8');
        } catch {}
    }

    console.log(`[Definitions] Fetching ${name} definition from remote URL: ${url}`);
    const response = await fetch(url);
    if (!response.ok) {
        // Fallback to disk cache if available even if expired
        if (fs.existsSync(cacheFile)) {
            console.warn(`[Definitions] Remote fetch failed (${response.status}), falling back to disk cache.`);
            return fs.readFileSync(cacheFile, 'utf-8');
        }
        throw new Error(`Failed to fetch ${name} definition: HTTP ${response.status}`);
    }

    const content = await response.text();
    try {
        fs.writeFileSync(cacheFile, content, 'utf-8');
    } catch (err) {
        console.error(`[Definitions] Error writing disk cache for ${name}:`, err);
    }

    return content;
}
