/**
 * Inlines the built frontend into a TypeScript module so the packaged binary
 * can serve the UI without a dist/ folder beside it.
 *
 * The packaged executable is a Node SEA blob: it carries the bundled server
 * script and nothing else, so `dist/` simply does not exist at runtime. Rather
 * than asking users to keep a folder next to the binary, the whole frontend
 * (8 files, ~600K) is base64'd into the bundle at build time.
 *
 * Run by `npm run package:bundle` after `vite build`. In dev the generated
 * module is an empty map and the server falls back to reading dist/ off disk,
 * so `node server.ts` keeps picking up rebuilds without re-running this.
 */
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const distDir = path.join(root, 'dist');
const outFile = path.join(root, 'server', 'embedded-frontend.generated.ts');

/** Only the types Vite actually emits for this app. */
const CONTENT_TYPES = {
    '.html': 'text/html; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.css': 'text/css; charset=utf-8',
    '.woff2': 'font/woff2',
    '.woff': 'font/woff',
    '.svg': 'image/svg+xml',
    '.png': 'image/png',
    '.ico': 'image/x-icon',
    '.json': 'application/json; charset=utf-8',
    '.map': 'application/json; charset=utf-8'
};

function walk(dir) {
    const out = [];
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            out.push(...walk(full));
        } else if (entry.isFile()) {
            out.push(full);
        }
    }
    return out;
}

const header = `// GENERATED by scripts/embed-dist.mjs — do not edit.
// Regenerate with \`npm run embed:dist\` (runs automatically during packaging).
`;

const PLACEHOLDER = `${header}//
// Checked in empty on purpose: \`node server.ts\` serves dist/ off disk so dev
// rebuilds are picked up live, and typecheck needs the module to resolve
// before any packaging has run.
export type EmbeddedFile = { contentType: string; body: string };

export const EMBEDDED_FRONTEND: Record<string, EmbeddedFile> = {};
`;

// Packaging restores the placeholder once esbuild has read the populated file,
// so a build never leaves a multi-megabyte diff in the working tree.
if (process.argv.includes('--reset')) {
    fs.writeFileSync(outFile, PLACEHOLDER, 'utf-8');
    console.log(`[embed-dist] Reset ${path.relative(root, outFile)} to its empty placeholder.`);
    process.exit(0);
}

if (!fs.existsSync(distDir)) {
    throw new Error(`dist/ not found at ${distDir} — run \`npm run build\` first.`);
}

const files = walk(distDir);
if (files.length === 0) {
    throw new Error(`dist/ at ${distDir} is empty — run \`npm run build\` first.`);
}

const entries = [];
let totalBytes = 0;
for (const file of files.sort()) {
    // Keys are request paths ('/assets/index-abc.js'), so posix separators
    // regardless of the platform the build ran on.
    const key = '/' + path.relative(distDir, file).split(path.sep).join('/');
    const ext = path.extname(file).toLowerCase();
    const contentType = CONTENT_TYPES[ext] ?? 'application/octet-stream';
    const body = fs.readFileSync(file).toString('base64');
    totalBytes += fs.statSync(file).size;
    entries.push(
        `    ${JSON.stringify(key)}: { contentType: ${JSON.stringify(contentType)}, body: ${JSON.stringify(body)} }`
    );
}

const source =
    header +
    'export type EmbeddedFile = { contentType: string; body: string };\n\n' +
    'export const EMBEDDED_FRONTEND: Record<string, EmbeddedFile> = {\n' +
    entries.join(',\n') +
    '\n};\n';

fs.writeFileSync(outFile, source, 'utf-8');
console.log(
    `[embed-dist] Embedded ${files.length} files (${(totalBytes / 1024).toFixed(0)}K) into ${path.relative(root, outFile)}`
);
